### PR TITLE
Convert pyodide result to string if is a PyProxy - Fix #3

### LINKED ISSUE #3: Worker postMessage error for output such as NumPy arrays
Quite basic pieces of code such as

```
import numpy as np
np.array([1,2,3])
```
Give a confusing error message because the output can't be handled.

```
failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': [object Object] could not be cloned
```

There is a solution mentioned [in this pyodide issue](https://github.com/pyodide/pyodide/issues/1620) to use `.toString()` if the pyodide result is a PyProxy (`isPyProxy()`)

### PR DESCRIPTION
**Pull request by chrismgraham**

### CODE REVIEW

**Comment by christianp** [comment]
I don't think this is a good idea, and I deliberately didn't do it. I would prefer to detect numpy arrays and convert them to JS lists.

**Comment by chrismgraham** [comment]
It's not just numpy arrays though; here are two more that trigger the same error and are fixed by this:

```
import sys
sys.stdout
```
```
lambda x: x * 2
```

**Comment by christianp** [comment]
They're only "fixed" in the sense that the error message is avoided. The returned string isn't very usable.

**Comment by chrismgraham** [comment]
It's not, but triggering an error is stopping anything correctly set above such a line being marked, and in addition offering a confusing message.

If I've been asked to define a function and respond. with this 
```
def f(x):
    return x**2
lambda x: x * 2
```
then although it would be a bit of an unusual response, there's no 'error' in that code and so seems reasonable to get to the marking tests.

**Comment by christianp** [comment]
Then catch the error! I'm not saying do nothing, I'm saying that this solution isn't good enough.

**Comment by chrismgraham** [comment]
Ok, fair enough, and can see you're working on a better solution in a new branch - thanks

**Comment by christianp** [comment]
I'm sorry to pooh-pooh your first PR, but I think it's important not to set up bigger problems down the line with bodges.

**Pull request closed without merging**
